M48
; DRILL file {KiCad 7.0.2} date Tue Feb 27 00:06:30 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-27T00:06:30-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X92.5Y-60.0
X92.5Y-116.0
X142.5Y-60.0
X142.5Y-116.0
T0
M30
